spring:
  profiles: development
  active: development
  datasource:
    url: jdbc:postgresql://localhost:54321/postgres
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: spring_boot_with_tdd